-- ============================================================================
-- BITACORA_AUDITORIA_DEVENGO
-- Tabla de bitácora para auditoría de devengos.
-- Ejecutar con el esquema correspondiente (ej. ESIACOM).
-- ============================================================================

CREATE TABLE BITACORA_AUDITORIA_DEVENGO (
    ID                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CREDITO           VARCHAR2(20)   NOT NULL,
    CICLO             VARCHAR2(20)   NOT NULL,
    FECHA_PROCESADA   DATE           NOT NULL,
    TIPO_EJECUCION    VARCHAR2(20)   NOT NULL,  -- 'INDIVIDUAL' | 'MASIVO'
    USUARIO           VARCHAR2(50)   NOT NULL,
    PERFIL            VARCHAR2(50)   NOT NULL,
    IP                VARCHAR2(45),
    HASH_EJECUCION    VARCHAR2(64),
    FECHA_EJECUCION   TIMESTAMP      DEFAULT SYSTIMESTAMP,
    RESULTADO         VARCHAR2(20)   NOT NULL,  -- 'OK' | 'ERROR'
    MENSAJE_ERROR     VARCHAR2(4000)
);

CREATE INDEX IDX_BAD_CREDITO_CICLO ON BITACORA_AUDITORIA_DEVENGO (CREDITO, CICLO);
CREATE INDEX IDX_BAD_FECHA_EJECUCION ON BITACORA_AUDITORIA_DEVENGO (FECHA_EJECUCION);

COMMENT ON TABLE BITACORA_AUDITORIA_DEVENGO IS 'Bitácora de ejecuciones SP_AUDITA_DEVENGO';
