-- ============================================================================
-- FOLIO_TARJETA
-- ============================================================================

CREATE TABLE FOLIO_TARJETA (
    ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CDGEM       VARCHAR2(6)   NOT NULL,
    CDGNS       VARCHAR2(6)   NOT NULL,
    CICLO       VARCHAR2(2)   NOT NULL,
    FOLIO       VARCHAR2(30)  NOT NULL,
    CDGCO       VARCHAR2(6)   NOT NULL,
    CDGOCPE     VARCHAR2(6),
    CDGPE       VARCHAR2(6)   NOT NULL,
    TIPO_MOV    VARCHAR2(20)  NOT NULL,
    MOTIVO      VARCHAR2(4000),
    ACTIVO      VARCHAR2(1)   DEFAULT 'S' NOT NULL,
    FECHA       TIMESTAMP     DEFAULT CAST((SYSTIMESTAMP AT TIME ZONE 'America/Mexico_City') AS TIMESTAMP) NOT NULL
);


CREATE UNIQUE INDEX UK_FT_SUC_FOLIO ON FOLIO_TARJETA (CDGEM, CDGCO, FOLIO);
CREATE INDEX IDX_FT_CREDITO_CICLO ON FOLIO_TARJETA (CDGEM, CDGNS, CICLO);
CREATE INDEX IDX_FT_ACTIVOS ON FOLIO_TARJETA (CDGEM, CDGNS, CICLO, ACTIVO);


COMMENT ON TABLE FOLIO_TARJETA IS 'Histórico de folios de tarjetas de pago por crédito/ciclo';
COMMENT ON COLUMN FOLIO_TARJETA.CDGNS IS 'Crédito / grupo';
COMMENT ON COLUMN FOLIO_TARJETA.CICLO IS 'Ciclo del crédito';
COMMENT ON COLUMN FOLIO_TARJETA.FOLIO IS 'Número de folio de la tarjeta física';
COMMENT ON COLUMN FOLIO_TARJETA.CDGCO IS 'Sucursal al momento del evento (no se actualiza por reasignación)';
COMMENT ON COLUMN FOLIO_TARJETA.CDGOCPE IS 'Asesor asignado al crédito al momento del evento';
COMMENT ON COLUMN FOLIO_TARJETA.CDGPE IS 'Usuario que registró el movimiento';
COMMENT ON COLUMN FOLIO_TARJETA.TIPO_MOV IS 'ALTA | CAMBIO | ADICIONAL';
COMMENT ON COLUMN FOLIO_TARJETA.MOTIVO IS 'Justificación del movimiento';
COMMENT ON COLUMN FOLIO_TARJETA.ACTIVO IS 'S = folio vigente del ciclo; N = reemplazado (histórico)';

